version: '2'
services:
  web:
    build: .
    env_file: .env
    volumes:
      - .:/opt/oam-dynamic-tiler/
    ports:
      - "8002:8000"
    links:
      - postgis
    command: python app.py
  postgis:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=mapzen
      - POSTGRES_PASSWORD=mapzen
      - POSTGRES_DB=elevation
volumes:
  pgdata:
